# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cg2VU_EgzgX7hoeP2I_CF7QjNXxSN6qD
"""

from datetime import date
nome = str(input("Informe seu nome."))
atual = date.today().year
nasc=int(input("informe seu ano de nescimento"))
idade = atual - nasc
if idade <= 9:
  print("Olá {} você tem {} anos e sua categoria séra Mirim".format(nome,idade))
elif idade == 10 or idade <= 14:
  print("Olá {} vocÊ tem {} anos e sua categoria é Infantil".format(nome,idade))
elif idade ==15 or idade <= 19:
  print("Olá {} vocÊ tem {} anos e sua categoria é Junior".format(nome,idade))
elif idade ==20:
  print("Olá {} vocÊ tem {} com essa idade sua categoria é Senior".format(nome,idade))
else:
  print("Olá {} Sua categoria é master".format(nome))